-- AutoScheduler Database Schema
-- Run this in your Supabase SQL Editor

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text DEFAULT '',
  estimated_min integer NOT NULL,
  deadline timestamptz,
  priority text NOT NULL CHECK (priority IN ('Low', 'Medium', 'High')),
  completed boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  split_group_id uuid NULL,
  split_index integer NULL
);

-- People notes (linked to tasks)
CREATE TABLE IF NOT EXISTS people_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  person_name text NOT NULL,
  note_text text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Schedule slots (auto-generated by scheduler)
CREATE TABLE IF NOT EXISTS schedule_slots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  locked boolean DEFAULT false
);

-- Settings (singleton row)
CREATE TABLE IF NOT EXISTS settings (
  id integer PRIMARY KEY CHECK (id = 1),
  work_day_start text DEFAULT '09:00',
  work_day_end text DEFAULT '17:00',
  include_saturday boolean DEFAULT false,
  include_sunday boolean DEFAULT false,
  theme text DEFAULT 'light',
  accent_color text DEFAULT '#3b82f6',
  auto_split_tasks boolean DEFAULT false,
  scheduler_active boolean DEFAULT false,
  lunch_start text DEFAULT '12:00',
  lunch_end text DEFAULT '13:00'
);

-- Seed the singleton settings row
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Disable RLS on all tables (single-user app)
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE people_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create permissive policies for anon access
CREATE POLICY "Allow all on tasks" ON tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on people_notes" ON people_notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on schedule_slots" ON schedule_slots FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on settings" ON settings FOR ALL USING (true) WITH CHECK (true);

-- Migration: add auto-split columns if upgrading from an earlier schema
-- ALTER TABLE tasks ADD COLUMN IF NOT EXISTS split_group_id uuid NULL;
-- ALTER TABLE tasks ADD COLUMN IF NOT EXISTS split_index integer NULL;
-- ALTER TABLE settings ADD COLUMN IF NOT EXISTS auto_split_tasks boolean NOT NULL DEFAULT false;
-- ALTER TABLE settings ADD COLUMN IF NOT EXISTS scheduler_active boolean NOT NULL DEFAULT false;
-- ALTER TABLE settings ADD COLUMN IF NOT EXISTS lunch_start text NOT NULL DEFAULT '12:00';
-- ALTER TABLE settings ADD COLUMN IF NOT EXISTS lunch_end text NOT NULL DEFAULT '13:00';

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_people_notes_task_id ON people_notes(task_id);
CREATE INDEX IF NOT EXISTS idx_schedule_slots_task_id ON schedule_slots(task_id);
CREATE INDEX IF NOT EXISTS idx_schedule_slots_start_time ON schedule_slots(start_time);
CREATE INDEX IF NOT EXISTS idx_tasks_completed ON tasks(completed);
